### ISSUE TITLE
Multi-variate OI

### ISSUE THREAD

**Issue by tnipen** [metno/gridpp#102]
- [x] Rename variables (pbackground, pbackground_corr)
- [x] Use consistently std or variance (check what the other oi functions do).
- [x] Use MultiStructure instead of MixA. This requires a new Soar class (see example how to do this in Barnes).
- [x] Add another parameter in StartedBoxCox (to allow the linear part to end at a different value)
- [x] Test how to pass structure functions in R (@tnipen)

**Comment by cristianlussana** [comment]
@tnipen Done (branch oi_ensi_multi). I have also edited https://github.com/metno/gridpp/wiki/Gridpp-in-R
