### ISSUE TITLE
Consider moving away from Travis

### ISSUE THREAD

**Issue by joewkr** [metno/gridpp#63]
Currently gridpp uses [travis-ci.org](https://travis-ci.org/) for CI, but travis-ci.org is planned to be phased out on 31 Decmeber 2020 and users are advised to migrate to travis-ci.com which will be used for both open-source and private repos. But the thing is that with recent change in the pricing model ([https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)) they introduce some mumbo jumbo with 10000 credits for OSS projects (and I'm not sure whether it's a monthly quota or one-time deal). Thus currently Travis doesn't look as the best option for running open-source projects CI, maybe it's time to look for better alternatives.

**Comment by trygveasp** [comment]
I have good experiences with moving to github's actions. Stopped testing pysurfex on travis since it had to be migrated to .com for METNO anyway. Did the migration on a private project and that was ok enough.

**Comment by tnipen** [comment]
Thanks for the input guys!
